import java.beans.PropertyVetoException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Tend
 */
public class Availablebus extends javax.swing.JInternalFrame {

    
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    String id;
    public Availablebus() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/buse-ticketing","root","");
            
            String query =
                    "SELECT * FROM bus";
            
            PreparedStatement preparedStatement = con.prepareStatement(query);
            ResultSet rs = preparedStatement.executeQuery();
            

            while(rs.next()){
                String busname = rs.getString("name");
                String numberplate = rs.getString("number_plate");
                 id= String.valueOf(rs.getInt("busid"));
                String availableseats = String.valueOf(rs.getInt("available_seat"));
                String source = rs.getString("source");
                String destination = rs.getString("destination");
                String route = source + " to " + destination;
                 String price = "MWK"+String.valueOf(rs.getFloat("price"));
                String time = rs.getString("departure_time");
                String arrival =  rs.getString("arrival_time");


                String tbData[] = {busname,numberplate,availableseats,route,price,time,arrival};
                DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();

                tblModel.addRow(tbData);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Availablebus.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Availablebus.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        message = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(770, 520));
        setRequestFocusEnabled(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 204));
        jLabel1.setText("AVAILABLE BUSES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 0, -1, 28));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BUS NAME", "NUMBER PLATE", "AVAILABLE SEATS", "ROUTE ", "PRICE", "DEPARTURE TIME", "ARRIVAL TIME"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 740, 170));

        jButton3.setText("SELECT BUS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, -1, -1));

        message.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        message.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 250, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      
        boolean booked = false;
        int selectedRow = jTable1.getSelectedRow();
        String busName = (String) jTable1.getValueAt(selectedRow,0);
        try{
            int a = 0,total = 0;
            String query = "SELECT available_seat,total_seat FROM bus WHERE name = '"+busName+"'";
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/buse-ticketing","root","");
            Statement output = con.createStatement();
            ResultSet result = output.executeQuery(query);
            while(result.next()){
                a = result.getInt("available_seat");
                total = result.getInt("total_seat");
            }
            if(a != 0){
                int num = total - a;
                a--;
                query = "UPDATE `bus` SET `available_seat` = '"+a+"' WHERE name = '"+busName+"'";
                output.executeUpdate(query);

                JOptionPane.showMessageDialog(this,"Your seat number is "+num);
                JOptionPane.showMessageDialog(this, "Record updated sucessfully");
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setValueAt(a,selectedRow,2);
                booked = true;
            }
            else{
                JOptionPane.showMessageDialog(this, "THE BUS IS FULL SELECT ANOTHER"); 
            }
        }
        catch(Exception e){
            System.out.print(e);
        }
        if(booked != false){
            Pay tend= new Pay();
            tend.setVisible(true);
//            setVisible(false);
        }
        
//        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
//        if(jTable1.getSelectedRow() == -1){
//            if(jTable1.getRowCount() == 0){
//                message.setText("Table is empty");
//            }else{
//                message.setText("Select the product G");
//            }
//        }else{
//            try {
//            Class.forName("com.mysql.cj.jdbc.Driver");
//            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/buse-ticketing","root","");
//            
//            String query =
//                    "SELECT * FROM bus WHERE busid = '"+id+"' ";
//            
//            PreparedStatement preparedStatement = con.prepareStatement(query);
//            ResultSet rs = preparedStatement.executeQuery();
//            
//
//            while(rs.next()){
//                int availableseat = rs.getInt("available_seat");
//                int totalseat = rs.getInt("total_seat");
//                int seatnumber = totalseat-availableseat;
//                JOptionPane.showMessageDialog(this,"Your seat number is "+seatnumber);
//                int newavailableseat=availableseat-1;
//                
//             String sql = "UPDATE bus set available_seat = '" +  newavailableseat+ "' WHERE busid = '"+id+"'";
//
//        try{
//            Class.forName("com.mysql.cj.jdbc.Driver");
//            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/buse-ticketing","root","");
//            pst = conn.prepareStatement(sql);
//            pst.execute();
//            JOptionPane.showMessageDialog(this, "Record updated sucessfully");
//            
//        }catch(Exception exception){
//            JOptionPane.showMessageDialog(this, "Database error: " + exception.getMessage());
//        }
//   }
//            
//        } catch (SQLException ex) {
//            Logger.getLogger(Availablebus.class.getName()).log(Level.SEVERE, null, ex);
//        }   catch (ClassNotFoundException ex) {
//                Logger.getLogger(Availablebus.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        }
        
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel message;
    // End of variables declaration//GEN-END:variables
}
